spring.application.name=NurseBookingSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/nurse_booking_db
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
