package com.harsh.nursebookingsystem.user.domain;

import com.harsh.nursebookingsystem.nurse.domain.NurseProfile;
import com.harsh.nursebookingsystem.patient.domain.PatientProfile;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;
import java.util.UUID;

/**
 * The shared account for every person who can sign in to the platform.
 *
 * This entity deliberately contains only account data. Patient-specific and
 * nurse-specific details live in their own profile entities, preventing this
 * table from accumulating many irrelevant nullable columns.
 */
@Entity
@Table(name = "users")
public class User {

    // Primary key generated by Hibernate as a UUID rather than a sequential number.
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    // Jakarta Validation rules are applied later when a controller receives @Valid input.
    @Email
    // This will hold a password hash created by Spring Security, never a raw password.
    @NotBlank
    @Size(max = 255)
    @Column(nullable = false, unique = true, length = 255)
    private String email;

    @NotBlank
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    @Size(max = 30)
    @Column(name = "phone_number", length = 30)
    private String phoneNumber;

    // STRING stores values such as "PATIENT" in the database, which is safer than enum ordinals.
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private Role role;

    // Hibernate sets this once when the row is first inserted.
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    // Hibernate refreshes this whenever the entity is updated.
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    // "mappedBy" means the profile owns the database foreign key (patient_profiles.user_id).
    @OneToOne(mappedBy = "user")
    private PatientProfile patientProfile;

    // A user has at most one nurse profile; the unique foreign key enforces this in the database.
    @OneToOne(mappedBy = "user")
    private NurseProfile nurseProfile;

    // JPA needs a no-argument constructor to recreate an entity from a database row.
    public User() {
    }

    public UUID getId() { return id; }
    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }
    public String getPasswordHash() { return passwordHash; }
    public void setPasswordHash(String passwordHash) { this.passwordHash = passwordHash; }
    public String getPhoneNumber() { return phoneNumber; }
    public void setPhoneNumber(String phoneNumber) { this.phoneNumber = phoneNumber; }
    public Role getRole() { return role; }
    public void setRole(Role role) { this.role = role; }
    public Instant getCreatedAt() { return createdAt; }
    public Instant getUpdatedAt() { return updatedAt; }
    public PatientProfile getPatientProfile() { return patientProfile; }
    public NurseProfile getNurseProfile() { return nurseProfile; }
}
